import Head from 'next/head'

const Home = () => {
  return (
    <>
      <Head>
        <title>無限しりとり</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta
          content={'width=device-width, initial-scale=1'}
          name={'viewport'}
        />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>Hello</div>
    </>
  )
}

export default Home
